'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.1
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("eveC.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to An error has occured when updating the RSS Feed database.
        '''</summary>
        Friend ReadOnly Property FeedUpdateErrorMessage() As String
            Get
                Return ResourceManager.GetString("FeedUpdateErrorMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Program shutting down.
        '''</summary>
        Friend ReadOnly Property ProgramShuttingDown() As String
            Get
                Return ResourceManager.GetString("ProgramShuttingDown", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Program starting up.
        '''</summary>
        Friend ReadOnly Property ProgramStartingUp() As String
            Get
                Return ResourceManager.GetString("ProgramStartingUp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to An error has occured while attempting to download the latest RSS Feed information.
        '''</summary>
        Friend ReadOnly Property RssFeedDownloadErrorMessage() As String
            Get
                Return ResourceManager.GetString("RssFeedDownloadErrorMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to RSS Feed Update Error.
        '''</summary>
        Friend ReadOnly Property RSSFeedUpdateError() As String
            Get
                Return ResourceManager.GetString("RSSFeedUpdateError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Oops an unhandled error has occured. It&apos;s ok though, the error has been logged.
        '''</summary>
        Friend ReadOnly Property UnhandledExceptionMessage() As String
            Get
                Return ResourceManager.GetString("UnhandledExceptionMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unhandled Exception.
        '''</summary>
        Friend ReadOnly Property UnhandledExceptionTitle() As String
            Get
                Return ResourceManager.GetString("UnhandledExceptionTitle", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
