
'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Objects
Imports System.Data.Objects.DataClasses
Imports System.Data.EntityClient
Imports System.ComponentModel
Imports System.Xml.Serialization
Imports System.Runtime.Serialization

<Assembly: EdmSchemaAttribute("52166632-34b7-4973-8755-0be6ba310eba")>
#Region "EDM Relationship Metadata"
<Assembly: EdmRelationshipAttribute("rssFeedsModel", "fk_channel_newsItem", "channel", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(channel), "newsItem", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(newsItem), True)>
<Assembly: EdmRelationshipAttribute("rssFeedsModel", "fk_definer_channel", "definer", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(definer), "channel", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(channel), True)>
<Assembly: EdmRelationshipAttribute("rssFeedsModel", "fk_version_channel", "version", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(version), "channel", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(channel), True)>

#End Region

#Region "Contexts"

''' <summary>
''' No Metadata Documentation available.
''' </summary>
Public Partial Class rssFeedsEntities
    Inherits ObjectContext

    #Region "Constructors"

    ''' <summary>
    ''' Initializes a new rssFeedsEntities object using the connection string found in the 'rssFeedsEntities' section of the application configuration file.
    ''' </summary>
    Public Sub New()
        MyBase.New("name=rssFeedsEntities", "rssFeedsEntities")
    MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Initialize a new rssFeedsEntities object.
    ''' </summary>
    Public Sub New(ByVal connectionString As String)
        MyBase.New(connectionString, "rssFeedsEntities")
    MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Initialize a new rssFeedsEntities object.
    ''' </summary>
    Public Sub New(ByVal connection As EntityConnection)
        MyBase.New(connection, "rssFeedsEntities")
    MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    #End Region

    #Region "Partial Methods"

    Partial Private Sub OnContextCreated()
    End Sub

    #End Region

    #Region "ObjectSet Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property channels() As ObjectSet(Of channel)
        Get
            If (_channels Is Nothing) Then
                _channels = MyBase.CreateObjectSet(Of channel)("channels")
            End If
            Return _channels
        End Get
    End Property

    Private _channels As ObjectSet(Of channel)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property newsItems() As ObjectSet(Of newsItem)
        Get
            If (_newsItems Is Nothing) Then
                _newsItems = MyBase.CreateObjectSet(Of newsItem)("newsItems")
            End If
            Return _newsItems
        End Get
    End Property

    Private _newsItems As ObjectSet(Of newsItem)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property definers() As ObjectSet(Of definer)
        Get
            If (_definers Is Nothing) Then
                _definers = MyBase.CreateObjectSet(Of definer)("definers")
            End If
            Return _definers
        End Get
    End Property

    Private _definers As ObjectSet(Of definer)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property versions() As ObjectSet(Of version)
        Get
            If (_versions Is Nothing) Then
                _versions = MyBase.CreateObjectSet(Of version)("versions")
            End If
            Return _versions
        End Get
    End Property

    Private _versions As ObjectSet(Of version)

    #End Region
    #Region "AddTo Methods"

    ''' <summary>
    ''' Deprecated Method for adding a new object to the channels EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddTochannels(ByVal channel As channel)
        MyBase.AddObject("channels", channel)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the newsItems EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddTonewsItems(ByVal newsItem As newsItem)
        MyBase.AddObject("newsItems", newsItem)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the definers EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddTodefiners(ByVal definer As definer)
        MyBase.AddObject("definers", definer)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the versions EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToversions(ByVal version As version)
        MyBase.AddObject("versions", version)
    End Sub

    #End Region
End Class

#End Region
#Region "Entities"

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="rssFeedsModel", Name:="channel")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class channel
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new channel object.
    ''' </summary>
    ''' <param name="id">Initial value of the id property.</param>
    ''' <param name="title">Initial value of the title property.</param>
    ''' <param name="url">Initial value of the url property.</param>
    ''' <param name="lastUpdate">Initial value of the lastUpdate property.</param>
    ''' <param name="definerId">Initial value of the definerId property.</param>
    ''' <param name="versionId">Initial value of the versionId property.</param>
    ''' <param name="test">Initial value of the test property.</param>
    Public Shared Function Createchannel(id As Global.System.Int32, title As Global.System.String, url As Global.System.String, lastUpdate As Global.System.DateTime, definerId As Global.System.Int32, versionId As Global.System.Int32, test As Global.System.Guid) As channel
        Dim channel as channel = New channel
        channel.id = id
        channel.title = title
        channel.url = url
        channel.lastUpdate = lastUpdate
        channel.definerId = definerId
        channel.versionId = versionId
        channel.test = test
        Return channel
    End Function

    #End Region
    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property id() As Global.System.Int32
        Get
            Return _id
        End Get
        Set
            If (_id <> Value) Then
                OnidChanging(value)
                ReportPropertyChanging("id")
                _id = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("id")
                OnidChanged()
            End If
        End Set
    End Property

    Private _id As Global.System.Int32
    Private Partial Sub OnidChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnidChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property title() As Global.System.String
        Get
            Return _title
        End Get
        Set
            OntitleChanging(value)
            ReportPropertyChanging("title")
            _title = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("title")
            OntitleChanged()
        End Set
    End Property

    Private _title As Global.System.String
    Private Partial Sub OntitleChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OntitleChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property url() As Global.System.String
        Get
            Return _url
        End Get
        Set
            OnurlChanging(value)
            ReportPropertyChanging("url")
            _url = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("url")
            OnurlChanged()
        End Set
    End Property

    Private _url As Global.System.String
    Private Partial Sub OnurlChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnurlChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property lastUpdate() As Global.System.DateTime
        Get
            Return _lastUpdate
        End Get
        Set
            OnlastUpdateChanging(value)
            ReportPropertyChanging("lastUpdate")
            _lastUpdate = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("lastUpdate")
            OnlastUpdateChanged()
        End Set
    End Property

    Private _lastUpdate As Global.System.DateTime
    Private Partial Sub OnlastUpdateChanging(value As Global.System.DateTime)
    End Sub

    Private Partial Sub OnlastUpdateChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property definerId() As Global.System.Int32
        Get
            Return _definerId
        End Get
        Set
            OndefinerIdChanging(value)
            ReportPropertyChanging("definerId")
            _definerId = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("definerId")
            OndefinerIdChanged()
        End Set
    End Property

    Private _definerId As Global.System.Int32
    Private Partial Sub OndefinerIdChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OndefinerIdChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property versionId() As Global.System.Int32
        Get
            Return _versionId
        End Get
        Set
            OnversionIdChanging(value)
            ReportPropertyChanging("versionId")
            _versionId = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("versionId")
            OnversionIdChanged()
        End Set
    End Property

    Private _versionId As Global.System.Int32
    Private Partial Sub OnversionIdChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnversionIdChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property test() As Global.System.Guid
        Get
            Return _test
        End Get
        Set
            OntestChanging(value)
            ReportPropertyChanging("test")
            _test = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("test")
            OntestChanged()
        End Set
    End Property

    Private _test As Global.System.Guid
    Private Partial Sub OntestChanging(value As Global.System.Guid)
    End Sub

    Private Partial Sub OntestChanged()
    End Sub

    #End Region
    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("rssFeedsModel", "fk_channel_newsItem", "newsItem")>
     Public Property newsItems() As EntityCollection(Of newsItem)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of newsItem)("rssFeedsModel.fk_channel_newsItem", "newsItem")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of newsItem)("rssFeedsModel.fk_channel_newsItem", "newsItem", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("rssFeedsModel", "fk_definer_channel", "definer")>
    Public Property definer() As definer
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of definer)("rssFeedsModel.fk_definer_channel", "definer").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of definer)("rssFeedsModel.fk_definer_channel", "definer").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property definerReference() As EntityReference(Of definer)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of definer)("rssFeedsModel.fk_definer_channel", "definer")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of definer)("rssFeedsModel.fk_definer_channel", "definer", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("rssFeedsModel", "fk_version_channel", "version")>
    Public Property version() As version
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of version)("rssFeedsModel.fk_version_channel", "version").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of version)("rssFeedsModel.fk_version_channel", "version").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property versionReference() As EntityReference(Of version)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of version)("rssFeedsModel.fk_version_channel", "version")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of version)("rssFeedsModel.fk_version_channel", "version", value)
            End If
        End Set
    End Property

    #End Region
End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="rssFeedsModel", Name:="definer")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class definer
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new definer object.
    ''' </summary>
    ''' <param name="id">Initial value of the id property.</param>
    ''' <param name="names">Initial value of the names property.</param>
    Public Shared Function Createdefiner(id As Global.System.Int32, names As Global.System.String) As definer
        Dim definer as definer = New definer
        definer.id = id
        definer.names = names
        Return definer
    End Function

    #End Region
    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property id() As Global.System.Int32
        Get
            Return _id
        End Get
        Set
            If (_id <> Value) Then
                OnidChanging(value)
                ReportPropertyChanging("id")
                _id = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("id")
                OnidChanged()
            End If
        End Set
    End Property

    Private _id As Global.System.Int32
    Private Partial Sub OnidChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnidChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property names() As Global.System.String
        Get
            Return _names
        End Get
        Set
            OnnamesChanging(value)
            ReportPropertyChanging("names")
            _names = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("names")
            OnnamesChanged()
        End Set
    End Property

    Private _names As Global.System.String
    Private Partial Sub OnnamesChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnnamesChanged()
    End Sub

    #End Region
    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("rssFeedsModel", "fk_definer_channel", "channel")>
     Public Property channels() As EntityCollection(Of channel)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of channel)("rssFeedsModel.fk_definer_channel", "channel")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of channel)("rssFeedsModel.fk_definer_channel", "channel", value)
            End If
        End Set
    End Property

    #End Region
End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="rssFeedsModel", Name:="newsItem")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class newsItem
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new newsItem object.
    ''' </summary>
    ''' <param name="id">Initial value of the id property.</param>
    ''' <param name="title">Initial value of the title property.</param>
    ''' <param name="content">Initial value of the content property.</param>
    ''' <param name="getDate">Initial value of the getDate property.</param>
    ''' <param name="channelId">Initial value of the channelId property.</param>
    Public Shared Function CreatenewsItem(id As Global.System.Int32, title As Global.System.String, content As Global.System.String, getDate As Global.System.DateTime, channelId As Global.System.Int32) As newsItem
        Dim newsItem as newsItem = New newsItem
        newsItem.id = id
        newsItem.title = title
        newsItem.content = content
        newsItem.getDate = getDate
        newsItem.channelId = channelId
        Return newsItem
    End Function

    #End Region
    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property id() As Global.System.Int32
        Get
            Return _id
        End Get
        Set
            If (_id <> Value) Then
                OnidChanging(value)
                ReportPropertyChanging("id")
                _id = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("id")
                OnidChanged()
            End If
        End Set
    End Property

    Private _id As Global.System.Int32
    Private Partial Sub OnidChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnidChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property title() As Global.System.String
        Get
            Return _title
        End Get
        Set
            OntitleChanging(value)
            ReportPropertyChanging("title")
            _title = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("title")
            OntitleChanged()
        End Set
    End Property

    Private _title As Global.System.String
    Private Partial Sub OntitleChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OntitleChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property content() As Global.System.String
        Get
            Return _content
        End Get
        Set
            OncontentChanging(value)
            ReportPropertyChanging("content")
            _content = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("content")
            OncontentChanged()
        End Set
    End Property

    Private _content As Global.System.String
    Private Partial Sub OncontentChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OncontentChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property getDate() As Global.System.DateTime
        Get
            Return _getDate
        End Get
        Set
            OngetDateChanging(value)
            ReportPropertyChanging("getDate")
            _getDate = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("getDate")
            OngetDateChanged()
        End Set
    End Property

    Private _getDate As Global.System.DateTime
    Private Partial Sub OngetDateChanging(value As Global.System.DateTime)
    End Sub

    Private Partial Sub OngetDateChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property channelId() As Global.System.Int32
        Get
            Return _channelId
        End Get
        Set
            OnchannelIdChanging(value)
            ReportPropertyChanging("channelId")
            _channelId = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("channelId")
            OnchannelIdChanged()
        End Set
    End Property

    Private _channelId As Global.System.Int32
    Private Partial Sub OnchannelIdChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnchannelIdChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property link() As Global.System.String
        Get
            Return _link
        End Get
        Set
            OnlinkChanging(value)
            ReportPropertyChanging("link")
            _link = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("link")
            OnlinkChanged()
        End Set
    End Property

    Private _link As Global.System.String
    Private Partial Sub OnlinkChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnlinkChanged()
    End Sub

    #End Region
    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("rssFeedsModel", "fk_channel_newsItem", "channel")>
    Public Property channel() As channel
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of channel)("rssFeedsModel.fk_channel_newsItem", "channel").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of channel)("rssFeedsModel.fk_channel_newsItem", "channel").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property channelReference() As EntityReference(Of channel)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of channel)("rssFeedsModel.fk_channel_newsItem", "channel")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of channel)("rssFeedsModel.fk_channel_newsItem", "channel", value)
            End If
        End Set
    End Property

    #End Region
End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="rssFeedsModel", Name:="version")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class version
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new version object.
    ''' </summary>
    ''' <param name="id">Initial value of the id property.</param>
    ''' <param name="name">Initial value of the name property.</param>
    Public Shared Function Createversion(id As Global.System.Int32, name As Global.System.String) As version
        Dim version as version = New version
        version.id = id
        version.name = name
        Return version
    End Function

    #End Region
    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property id() As Global.System.Int32
        Get
            Return _id
        End Get
        Set
            If (_id <> Value) Then
                OnidChanging(value)
                ReportPropertyChanging("id")
                _id = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("id")
                OnidChanged()
            End If
        End Set
    End Property

    Private _id As Global.System.Int32
    Private Partial Sub OnidChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnidChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property name() As Global.System.String
        Get
            Return _name
        End Get
        Set
            OnnameChanging(value)
            ReportPropertyChanging("name")
            _name = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("name")
            OnnameChanged()
        End Set
    End Property

    Private _name As Global.System.String
    Private Partial Sub OnnameChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnnameChanged()
    End Sub

    #End Region
    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("rssFeedsModel", "fk_version_channel", "channel")>
     Public Property channels() As EntityCollection(Of channel)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of channel)("rssFeedsModel.fk_version_channel", "channel")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of channel)("rssFeedsModel.fk_version_channel", "channel", value)
            End If
        End Set
    End Property

    #End Region
End Class

#End Region

