
'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Objects
Imports System.Data.Objects.DataClasses
Imports System.Data.EntityClient
Imports System.ComponentModel
Imports System.Xml.Serialization
Imports System.Runtime.Serialization

<Assembly: EdmSchemaAttribute("242e7d60-bd4c-4f21-b80c-89c0c3b5f40a")>
#Region "EDM Relationship Metadata"
<Assembly: EdmRelationshipAttribute("rssFeedsModel", "fk_feed_item", "feed", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(feed), "item", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(newsItem), True)>

#End Region

#Region "Contexts"

''' <summary>
''' No Metadata Documentation available.
''' </summary>
Public Partial Class rssFeedsEntities
    Inherits ObjectContext

    #Region "Constructors"

    ''' <summary>
    ''' Initializes a new rssFeedsEntities object using the connection string found in the 'rssFeedsEntities' section of the application configuration file.
    ''' </summary>
    Public Sub New()
        MyBase.New("name=rssFeedsEntities", "rssFeedsEntities")
    MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Initialize a new rssFeedsEntities object.
    ''' </summary>
    Public Sub New(ByVal connectionString As String)
        MyBase.New(connectionString, "rssFeedsEntities")
    MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Initialize a new rssFeedsEntities object.
    ''' </summary>
    Public Sub New(ByVal connection As EntityConnection)
        MyBase.New(connection, "rssFeedsEntities")
    MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    #End Region

    #Region "Partial Methods"

    Partial Private Sub OnContextCreated()
    End Sub

    #End Region

    #Region "ObjectSet Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property feeds() As ObjectSet(Of feed)
        Get
            If (_feeds Is Nothing) Then
                _feeds = MyBase.CreateObjectSet(Of feed)("feeds")
            End If
            Return _feeds
        End Get
    End Property

    Private _feeds As ObjectSet(Of feed)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property newsItems() As ObjectSet(Of newsItem)
        Get
            If (_newsItems Is Nothing) Then
                _newsItems = MyBase.CreateObjectSet(Of newsItem)("newsItems")
            End If
            Return _newsItems
        End Get
    End Property

    Private _newsItems As ObjectSet(Of newsItem)

    #End Region
    #Region "AddTo Methods"

    ''' <summary>
    ''' Deprecated Method for adding a new object to the feeds EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddTofeeds(ByVal feed As feed)
        MyBase.AddObject("feeds", feed)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the newsItems EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddTonewsItems(ByVal newsItem As newsItem)
        MyBase.AddObject("newsItems", newsItem)
    End Sub

    #End Region
End Class

#End Region
#Region "Entities"

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="rssFeedsModel", Name:="feed")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class feed
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new feed object.
    ''' </summary>
    ''' <param name="id">Initial value of the id property.</param>
    ''' <param name="name">Initial value of the name property.</param>
    ''' <param name="lastUpdated">Initial value of the lastUpdated property.</param>
    Public Shared Function Createfeed(id As Global.System.Guid, name As Global.System.String, lastUpdated As Global.System.DateTime) As feed
        Dim feed as feed = New feed
        feed.id = id
        feed.name = name
        feed.lastUpdated = lastUpdated
        Return feed
    End Function

    #End Region
    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property id() As Global.System.Guid
        Get
            Return _id
        End Get
        Set
            If (_id <> Value) Then
                OnidChanging(value)
                ReportPropertyChanging("id")
                _id = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("id")
                OnidChanged()
            End If
        End Set
    End Property

    Private _id As Global.System.Guid
    Private Partial Sub OnidChanging(value As Global.System.Guid)
    End Sub

    Private Partial Sub OnidChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property name() As Global.System.String
        Get
            Return _name
        End Get
        Set
            OnnameChanging(value)
            ReportPropertyChanging("name")
            _name = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("name")
            OnnameChanged()
        End Set
    End Property

    Private _name As Global.System.String
    Private Partial Sub OnnameChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnnameChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property link() As Global.System.String
        Get
            Return _link
        End Get
        Set
            OnlinkChanging(value)
            ReportPropertyChanging("link")
            _link = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("link")
            OnlinkChanged()
        End Set
    End Property

    Private _link As Global.System.String
    Private Partial Sub OnlinkChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnlinkChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property description() As Global.System.String
        Get
            Return _description
        End Get
        Set
            OndescriptionChanging(value)
            ReportPropertyChanging("description")
            _description = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("description")
            OndescriptionChanged()
        End Set
    End Property

    Private _description As Global.System.String
    Private Partial Sub OndescriptionChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OndescriptionChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property lastUpdated() As Global.System.DateTime
        Get
            Return _lastUpdated
        End Get
        Set
            OnlastUpdatedChanging(value)
            ReportPropertyChanging("lastUpdated")
            _lastUpdated = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("lastUpdated")
            OnlastUpdatedChanged()
        End Set
    End Property

    Private _lastUpdated As Global.System.DateTime
    Private Partial Sub OnlastUpdatedChanging(value As Global.System.DateTime)
    End Sub

    Private Partial Sub OnlastUpdatedChanged()
    End Sub

    #End Region
    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("rssFeedsModel", "fk_feed_item", "item")>
     Public Property items() As EntityCollection(Of newsItem)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of newsItem)("rssFeedsModel.fk_feed_item", "item")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of newsItem)("rssFeedsModel.fk_feed_item", "item", value)
            End If
        End Set
    End Property

    #End Region
End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="rssFeedsModel", Name:="newsItem")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class newsItem
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new newsItem object.
    ''' </summary>
    ''' <param name="id">Initial value of the id property.</param>
    ''' <param name="title">Initial value of the title property.</param>
    ''' <param name="link">Initial value of the link property.</param>
    ''' <param name="dateAcquired">Initial value of the dateAcquired property.</param>
    ''' <param name="feedId">Initial value of the feedId property.</param>
    Public Shared Function CreatenewsItem(id As Global.System.Guid, title As Global.System.String, link As Global.System.String, dateAcquired As Global.System.DateTime, feedId As Global.System.Guid) As newsItem
        Dim newsItem as newsItem = New newsItem
        newsItem.id = id
        newsItem.title = title
        newsItem.link = link
        newsItem.dateAcquired = dateAcquired
        newsItem.feedId = feedId
        Return newsItem
    End Function

    #End Region
    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property id() As Global.System.Guid
        Get
            Return _id
        End Get
        Set
            If (_id <> Value) Then
                OnidChanging(value)
                ReportPropertyChanging("id")
                _id = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("id")
                OnidChanged()
            End If
        End Set
    End Property

    Private _id As Global.System.Guid
    Private Partial Sub OnidChanging(value As Global.System.Guid)
    End Sub

    Private Partial Sub OnidChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property title() As Global.System.String
        Get
            Return _title
        End Get
        Set
            OntitleChanging(value)
            ReportPropertyChanging("title")
            _title = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("title")
            OntitleChanged()
        End Set
    End Property

    Private _title As Global.System.String
    Private Partial Sub OntitleChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OntitleChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property description() As Global.System.String
        Get
            Return _description
        End Get
        Set
            OndescriptionChanging(value)
            ReportPropertyChanging("description")
            _description = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("description")
            OndescriptionChanged()
        End Set
    End Property

    Private _description As Global.System.String
    Private Partial Sub OndescriptionChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OndescriptionChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property link() As Global.System.String
        Get
            Return _link
        End Get
        Set
            OnlinkChanging(value)
            ReportPropertyChanging("link")
            _link = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("link")
            OnlinkChanged()
        End Set
    End Property

    Private _link As Global.System.String
    Private Partial Sub OnlinkChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnlinkChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property publishDate() As Nullable(Of Global.System.DateTime)
        Get
            Return _publishDate
        End Get
        Set
            OnpublishDateChanging(value)
            ReportPropertyChanging("publishDate")
            _publishDate = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("publishDate")
            OnpublishDateChanged()
        End Set
    End Property

    Private _publishDate As Nullable(Of Global.System.DateTime)
    Private Partial Sub OnpublishDateChanging(value As Nullable(Of Global.System.DateTime))
    End Sub

    Private Partial Sub OnpublishDateChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property author() As Global.System.String
        Get
            Return _author
        End Get
        Set
            OnauthorChanging(value)
            ReportPropertyChanging("author")
            _author = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("author")
            OnauthorChanged()
        End Set
    End Property

    Private _author As Global.System.String
    Private Partial Sub OnauthorChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnauthorChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property dateAcquired() As Global.System.DateTime
        Get
            Return _dateAcquired
        End Get
        Set
            OndateAcquiredChanging(value)
            ReportPropertyChanging("dateAcquired")
            _dateAcquired = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("dateAcquired")
            OndateAcquiredChanged()
        End Set
    End Property

    Private _dateAcquired As Global.System.DateTime
    Private Partial Sub OndateAcquiredChanging(value As Global.System.DateTime)
    End Sub

    Private Partial Sub OndateAcquiredChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property feedId() As Global.System.Guid
        Get
            Return _feedId
        End Get
        Set
            OnfeedIdChanging(value)
            ReportPropertyChanging("feedId")
            _feedId = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("feedId")
            OnfeedIdChanged()
        End Set
    End Property

    Private _feedId As Global.System.Guid
    Private Partial Sub OnfeedIdChanging(value As Global.System.Guid)
    End Sub

    Private Partial Sub OnfeedIdChanged()
    End Sub

    #End Region
    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("rssFeedsModel", "fk_feed_item", "feed")>
    Public Property feed() As feed
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of feed)("rssFeedsModel.fk_feed_item", "feed").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of feed)("rssFeedsModel.fk_feed_item", "feed").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property feedReference() As EntityReference(Of feed)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of feed)("rssFeedsModel.fk_feed_item", "feed")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of feed)("rssFeedsModel.fk_feed_item", "feed", value)
            End If
        End Set
    End Property

    #End Region
End Class

#End Region

