'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.1
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("evec.Common.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to EvE Command has been unable to auto-backup your settings. It is recommended that you make a manual backup.
        '''</summary>
        Friend ReadOnly Property AutoBackupErrorMessage() As String
            Get
                Return ResourceManager.GetString("AutoBackupErrorMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Backup Error.
        '''</summary>
        Friend ReadOnly Property BackupError() As String
            Get
                Return ResourceManager.GetString("BackupError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to EvE Command Updated.
        '''</summary>
        Friend ReadOnly Property EvECommandUpdated() As String
            Get
                Return ResourceManager.GetString("EvECommandUpdated", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to EvE Command has been updated. Would you like to backup the settings before proceeding? (Recommended).
        '''</summary>
        Friend ReadOnly Property EvECommandUpdatedMsg() As String
            Get
                Return ResourceManager.GetString("EvECommandUpdatedMsg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unable to write to log. Please check that the application has permission to access its directory folder.
        '''</summary>
        Friend ReadOnly Property LogErrorMessage() As String
            Get
                Return ResourceManager.GetString("LogErrorMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Log Write Error.
        '''</summary>
        Friend ReadOnly Property LogErrorTitle() As String
            Get
                Return ResourceManager.GetString("LogErrorTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Core Databases are missing from EvE Command. There is nothing for it but to reinstall EvE Command, Sorry. EvE Command will now shut down.
        '''</summary>
        Friend ReadOnly Property MissingDatabaseMsg() As String
            Get
                Return ResourceManager.GetString("MissingDatabaseMsg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Missing Databases.
        '''</summary>
        Friend ReadOnly Property MissingDatabases() As String
            Get
                Return ResourceManager.GetString("MissingDatabases", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Settings Corrupt.
        '''</summary>
        Friend ReadOnly Property SettingsCorruptTitle() As String
            Get
                Return ResourceManager.GetString("SettingsCorruptTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The settings file is either missing or corrupt. Would you like to load the last autosave of the settings file, made on {0}?.
        '''</summary>
        Friend ReadOnly Property SettingsFileCorrupt() As String
            Get
                Return ResourceManager.GetString("SettingsFileCorrupt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Settings Load Error.
        '''</summary>
        Friend ReadOnly Property SettingsLoadError() As String
            Get
                Return ResourceManager.GetString("SettingsLoadError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to EvE Command has been unable to load the selected settings file. An attempt to load a backup will be made.
        '''</summary>
        Friend ReadOnly Property SettingsLoadErrorMessage() As String
            Get
                Return ResourceManager.GetString("SettingsLoadErrorMessage", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
